# Alacritty
[colors.primary]
background = "#1f2f38"
foreground = "#aabbc4"

[colors.normal]
black   = "#1f2f38"
red     = "#dc657d"
green   = "#84b97c"
yellow  = "#d4b261"
blue    = "#639ee4"
magenta = "#b888e2"
cyan    = "#e18254"
white   = "#658595"

[colors.bright]
black   = "#263a45"
red     = "#e69ca0"
green   = "#4bb1a7"
yellow  = "#c7c18b"
blue    = "#72c7d1"
magenta = "#475c69"
cyan    = "#ae8785"
white   = "#aabbc4"
